/* =====================================================================
   RENZ STYLE SOLVE - FUNNEL LOADER
   Built 19 Sep 2026, 12:00. Do not edit this file by hand: it is generated by
   build-loader.py from the funnel source and overwritten on every build.

   The page that loads this needs one tag, once:

     <div id="rz-upsell-mount"></div>
     <script src="https://franklow1.github.io/renz-funnel/upsell.js" defer></script>

   Everything else lives here.
   ===================================================================== */
(function(){
  "use strict";
  /* a second copy of this tag on the same page would build a second quiz */
  var FLAG = "__RZ_LOADED_" + "rz_upsell_mount";
  if (window[FLAG]) return;
  window[FLAG] = true;

  var MOUNT_ID = "rz-upsell-mount";
  var CSS  = /*@CSS@*/;
  var HTML = /*@HTML@*/;

  /* The typefaces were linked from inside the markup this file injects, and that markup
     lands in the body, so a browser could not even ask for them until the whole script
     had arrived and painted. The links go into the head the moment this file is parsed,
     and out of the string, so nothing is asked for twice. */
  HTML = (function(html){
    try{
      var head = document.head || document.getElementsByTagName('head')[0];
      if(!head) return html;
      return html.replace(/<link\b[^>]*>\s*/gi, function(tag){
        try{
          var box = document.createElement('div');
          box.innerHTML = tag;
          var l = box.firstChild;
          if(!l || !l.getAttribute) return '';
          var href = l.getAttribute('href') || '';
          if(href && head.querySelector('link[href="' + href.replace(/"/g,'\\"') + '"]')) return '';
          head.appendChild(l);
        }catch(e){}
        return '';
      });
    }catch(e){}
    return html;
  })(HTML);

  /* ------------------------------------------------------------------
     WHERE THIS PAINTS, AND WHEN

     The host is a server rendered Vue app, and the div we are meant to
     paint into is part of the markup that app is about to take ownership
     of. Write into it too early and the hand over fails. What dies is
     their order form: no total, no card field, no way to pay, and not one
     line in the console to say so.

     Waiting for their app would mean holding a blank page in front of a
     man who just clicked an advert, so we do not wait to paint. The funnel
     is painted at once into a sheet of its own, laid over the page, which
     is exactly what the quiz looks like anyway. Then, once their checkout
     has actually drawn itself, the sheet is lifted into place in the page
     and the cover comes off. He sees none of it.

     On a page with no host app there is nothing to wait for and nothing to
     move: it paints where it is told, as it always did.
     ------------------------------------------------------------------ */
  var HOST_ID   = 'rz-host';
  var HOST_ROOT = '__nuxt';    /* the element their app mounts on */
  var SETTLE    = 700;         /* a page with no checkout on it still gets a moment */
  var LIMIT     = 12000;       /* never leave the funnel floating over their page for good */
  /* Moving the sheet into the page while the host is still building its checkout is what
     emptied the order form and left it at zero pounds with no card field. On a page that
     has a checkout the wait is long, because there is nothing to lose by waiting: the man
     can already see and use the funnel while it floats. The measured time for the checkout
     to come alive is two to four seconds, so thirty is a lot of room for a bad line. */
  var ORDER_LIMIT = 30000;

  function hostRoot(){ return document.getElementById(HOST_ROOT); }
  function mountDiv(){ return document.getElementById(MOUNT_ID); }

  /* their app is up AND the piece of it that we can break is finished */
  var appSeen = 0;
  function hostReady(){
    var r = hostRoot();
    if (!r) return true;
    if (!r.__vue_app__) return false;
    if (!appSeen) appSeen = Date.now();
    var order = document.querySelector('.c-order, [id^="one-step-order-"]');
    if (order) return !!document.querySelector(
      '.payment-content section, iframe[src*="stripe"], .form-btn');
    return Date.now() - appSeen > SETTLE;
  }

  function sheet(){
    if (document.getElementById('rz-host-css')) return;
    var st = document.createElement('style');
    st.id = 'rz-host-css';
    st.appendChild(document.createTextNode(
      '#' + HOST_ID + '.rz-float{position:fixed;top:0;right:0;bottom:0;left:0;' +
      'z-index:2147483000;overflow-y:auto;-webkit-overflow-scrolling:touch;' +
      'background:#F4F1EA}'));
    (document.head || document.documentElement).appendChild(st);
  }

  /* The host page paints its own content, and its order form, in the second before this
     file has even finished downloading. A man saw a checkout he had not asked for, and a
     white page, and could scroll away from a quiz that had not arrived yet.

     So the paste snippet carries an opaque sheet of paper as inline CSS, which the browser
     honours on the first paint. This takes it away the moment there is a funnel underneath
     it instead. If this file never arrives, the sheet stays, which is the right failure:
     a blank page beats somebody's half drawn checkout. */
  function unveil(){
    try{
      var v = document.getElementById('rz-veil');
      if (v && v.parentNode) v.parentNode.removeChild(v);
      var vs = document.getElementById('rz-veil-css');
      if (vs && vs.parentNode) vs.parentNode.removeChild(vs);
    }catch(e){}
  }

  function paint(){
    try{
      var st = document.createElement('style');
      st.setAttribute('data-rz-funnel','1');
      st.appendChild(document.createTextNode(CSS));
      (document.head || document.documentElement).appendChild(st);
      sheet();
      var host = document.getElementById(HOST_ID);
      if (!host){
        host = document.createElement('div');
        host.id = HOST_ID;
      }
      if (hostRoot() && mountDiv()){
        /* their page: start over it, and go into the flow when it is safe */
        (document.body || document.documentElement).appendChild(host);
        host.className = 'rz-float';
      } else if (!host.parentNode){
        /* a bare page: where the tag sits, or failing that the end of the body */
        var m = mountDiv();
        if (m) m.appendChild(host);
        else {
          var sc = document.currentScript;
          if (sc && sc.parentNode) sc.parentNode.insertBefore(host, sc.nextSibling);
          else (document.body || document.documentElement).appendChild(host);
        }
      }
      host.innerHTML = HTML;
    }catch(e){
      if (window.console && console.error) console.error('[RZ] could not paint the funnel', e);
      return false;
    }
    return true;
  }

  /* lift the sheet into the page, keeping his place in it */
  function home(){
    var m = mountDiv(), h = document.getElementById(HOST_ID);
    /* Nothing to move is still settled. Returning quietly here once left anything waiting
       on the handover sat there until the fifteen second fallback fired. */
    if (!m || !h || h.parentNode === m) { settled(); return; }
    var inner = 0;
    try{ inner = h.scrollTop || 0; }catch(e){}
    m.appendChild(h);
    h.className = '';
    try{
      if (inner > 0){
        var top = Math.round(h.getBoundingClientRect().top + window.pageYOffset);
        window.scrollTo(0, top + inner);
      }
    }catch(e){}
    /* the quiz measures the room it has, and it has just been given a different one */
    try{ if (window.RZ && RZ.fitQuiz) RZ.fitQuiz(); }catch(e){}
    settled();
  }

  /* Moving this subtree re-parents everything in it, and a video player that has already
     wired itself to a node loses that node and refuses to start. Wistia says so out loud:
     "Could not find element in DOM. Failed to initialize video." So nothing that embeds
     anything is built until the funnel has stopped moving. */
  function settled(){
    if (window.__rzSettled) return;
    window.__rzSettled = true;
    try{ window.dispatchEvent(new Event('rz:settled')); }catch(e){}
  }
  window.__rzWhenSettled = function(fn){
    if (window.__rzSettled) { try{ fn(); }catch(e){} return; }
    var done = false;
    function go(){ if (done) return; done = true; try{ fn(); }catch(e){} }
    window.addEventListener('rz:settled', go, {once:true});
    /* a page that never settles still has to show its film */
    setTimeout(function(){ settled(); go(); }, 15000);
  };

  /* Wait for the host's checkout to finish drawing, then take the funnel out of its own
     floating sheet and put it into the page. Anything that wants to happen after that
     hands in a callback. */
  function handover(done){
    if (!hostRoot() || !mountDiv()) { settled(); if (done) done(); return; }
    var t0 = Date.now();
    (function poll(){
      var hasOrder = false;
      try{ hasOrder = !!document.querySelector('.c-order, [id^="one-step-order-"]'); }catch(e){}
      var budget = hasOrder ? ORDER_LIMIT : LIMIT;
      if (hostReady() || Date.now() - t0 > budget) { home(); if (done) done(); return; }
      setTimeout(poll, 40);
    })();
  }
  window.__rzHandover = handover;

  /* The builder's stock bump heading, "Upgrade Your Order & Save!", promises a saving
     nobody has quantified and shouts on a page that never shouts. Guarded twice: it only
     looks inside the builder's own bump container, and it only rewrites a line that
     actually matches the stock wording, so on a step that does not carry one it does
     nothing at all. Untested against the live upsell, which sits behind a payment. */
  function fixBumpHeading(){
    try{
      [].forEach.call(document.querySelectorAll(
        '.order-bump-container .main-section .headline, .order-bump-container .headline'), function(h){
        var t=(h.textContent||'').trim();
        if(!t || !/upgrade|save/i.test(t)) return;
        h.textContent='Add to your order';
      });
    }catch(e){}
  }

  function start(){
    if (!paint()) return;
    try{
      fixBumpHeading();
      var bh=setInterval(fixBumpHeading, 800);
      setTimeout(function(){ clearInterval(bh); }, 60000);
    }catch(e){}
    /* the funnel's own code, verbatim, with the markup already on the page */
    (function(){
      'use strict';

      /* GoHighLevel's One Step Order element on this step. Sticky contact carries his name
         and email across from the checkout, so he is not typing them a second time. */
      var FORM = '#one-step-order-U3AtvyuBgg, [id^="one-step-order-"]';
      /* where a man goes when he says no. He has already paid for the call, so this must
         never be a dead end. */
      var SKIP = 'https://lorenzosegor.com/thank-you';
      var MEDIA = '';                       /* Wistia id for Lorenzo's 75 seconds */

      function form(){
        try { return document.querySelector(FORM); } catch(e){ return null; }
      }

      /* the way out goes UNDER the form, never above it */
      function wayOut(){
        if (document.getElementById('rz-upsell-out')) return;
        var f = form();
        var out = document.createElement('div');
        out.id = 'rz-upsell-out';
        out.innerHTML = '<div class="in">' +
          '<a href="' + SKIP + '">No thanks, take me to my calendar</a>' +
          '<p>Your call is already paid for.</p>' +
          '<p class="alone">Skipping this changes nothing about it.</p>' +
          '</div>';
        if (f && f.parentNode){
          var block = f.closest('.c-section, section, .c-row') || f;
          if (block.parentNode) block.parentNode.insertBefore(out, block.nextSibling);
          else f.parentNode.insertBefore(out, f.nextSibling);
        } else {
          /* no form found yet: put it at the end so he can always leave */
          var me = document.getElementById('rz-upsell');
          if (me && me.parentNode) me.parentNode.insertBefore(out, me.nextSibling);
          if (window.console && console.warn){
            console.warn('[RZ upsell] no order form matched "' + FORM + '" yet. The way out ' +
              'has been put after the copy instead. Check the One Step Order element is on ' +
              'this step and that its id matches.');
          }
        }
      }

      function film(){
        if (!MEDIA) return;
        /* the loader may still lift this stage into the page, and a player built before that
           move loses the node it wired itself to */
        if (typeof window.__rzWhenSettled === 'function' && !window.__rzSettled){
          window.__rzWhenSettled(film); return;
        }
        var slot = document.getElementById('rzu-film');
        if (!slot) return;
        var p = document.createElement('wistia-player');
        p.setAttribute('media-id', MEDIA);
        slot.parentNode.replaceChild(p, slot);
        if (!document.querySelector('script[src*="player.js"]')){
          var s = document.createElement('script');
          s.src = 'https://fast.wistia.com/player.js';
          s.async = true;
          document.head.appendChild(s);
        }
      }

      function boot(){
        try{
          if (!document.querySelector('meta[name="viewport"]')){
            var mv = document.createElement('meta');
            mv.name = 'viewport';
            mv.content = 'width=device-width,initial-scale=1,viewport-fit=cover';
            (document.head || document.documentElement).appendChild(mv);
          }
        }catch(e){}
        film();
        /* The way out goes in straight away, after the copy, because a man who has just
           been pitched something he did not ask for must always be able to leave. It used
           to wait for the checkout to draw, or eighteen seconds, whichever came first, so
           there were eighteen seconds with no way out and nothing to buy.
           It is MOVED under the checkout below, once there is a checkout to move it under.

           The way out is put into the host's own markup, and their checkout is a server
           rendered app that has not taken it over yet. Put anything in there before it does
           and the hand over fails: the card field never draws and nobody can pay. So this
           waits for the checkout to be genuinely finished, which is the moment the pay
           button exists, and only then does the link go in under it. */
        wayOut();
        var tries = 0;
        var again = setInterval(function(){
          var live = false;
          try{ live = !!document.querySelector(
            '.payment-content section, iframe[src*="stripe"], .form-btn'); }catch(e){}
          if (!live){ if (++tries > 60) { clearInterval(again); wayOut(); } return; }
          clearInterval(again);
          wayOut();
          var out = document.getElementById('rz-upsell-out');
          var f = form();
          var block = f && (f.closest('.c-section, section, .c-row') || f);
          if (out && block && block.parentNode && out.previousElementSibling !== block){
            block.parentNode.insertBefore(out, block.nextSibling);
          }
        }, 300);
      }

      if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot, {once:true});
      else boot();
    })();
    unveil();
    /* A stage with a quiz on it keeps the host page covered until the man is through it,
       and asks for the handover itself. Everything else goes in as soon as it is safe. */
    if (!window.__RZ_DEFER_HOME) handover();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start, {once:true});
  } else {
    start();
  }
})();
