/* =====================================================================
   RENZ STYLE SOLVE - FUNNEL LOADER
   Built 19 Sep 2026, 11:58. Do not edit this file by hand: it is generated by
   build-loader.py from the funnel source and overwritten on every build.

   The page that loads this needs one tag, once:

     <div id="rz-thanks-mount"></div>
     <script src="https://franklow1.github.io/renz-funnel/thanks.js" defer></script>

   Everything else lives here.
   ===================================================================== */
(function(){
  "use strict";
  /* a second copy of this tag on the same page would build a second quiz */
  var FLAG = "__RZ_LOADED_" + "rz_thanks_mount";
  if (window[FLAG]) return;
  window[FLAG] = true;

  var MOUNT_ID = "rz-thanks-mount";
  var CSS  = /*@CSS@*/;
  var HTML = /*@HTML@*/;

  /* ------------------------------------------------------------------
     WHERE THIS PAINTS, AND WHEN

     The host is a server rendered Vue app, and the div we are meant to
     paint into is part of the markup that app is about to take ownership
     of. Write into it too early and the hand over fails. What dies is
     their order form: no total, no card field, no way to pay, and not one
     line in the console to say so.

     Waiting for their app would mean holding a blank page in front of a
     man who just clicked an advert, so we do not wait to paint. The funnel
     is painted at once into a sheet of its own, laid over the page, which
     is exactly what the quiz looks like anyway. Then, once their checkout
     has actually drawn itself, the sheet is lifted into place in the page
     and the cover comes off. He sees none of it.

     On a page with no host app there is nothing to wait for and nothing to
     move: it paints where it is told, as it always did.
     ------------------------------------------------------------------ */
  var HOST_ID   = 'rz-host';
  var HOST_ROOT = '__nuxt';    /* the element their app mounts on */
  var SETTLE    = 700;         /* a page with no checkout on it still gets a moment */
  var LIMIT     = 12000;       /* never leave the funnel floating over their page for good */
  /* Moving the sheet into the page while the host is still building its checkout is what
     emptied the order form and left it at zero pounds with no card field. On a page that
     has a checkout the wait is long, because there is nothing to lose by waiting: the man
     can already see and use the funnel while it floats. The measured time for the checkout
     to come alive is two to four seconds, so thirty is a lot of room for a bad line. */
  var ORDER_LIMIT = 30000;

  function hostRoot(){ return document.getElementById(HOST_ROOT); }
  function mountDiv(){ return document.getElementById(MOUNT_ID); }

  /* their app is up AND the piece of it that we can break is finished */
  var appSeen = 0;
  function hostReady(){
    var r = hostRoot();
    if (!r) return true;
    if (!r.__vue_app__) return false;
    if (!appSeen) appSeen = Date.now();
    var order = document.querySelector('.c-order, [id^="one-step-order-"]');
    if (order) return !!document.querySelector(
      '.payment-content section, iframe[src*="stripe"], .form-btn');
    return Date.now() - appSeen > SETTLE;
  }

  function sheet(){
    if (document.getElementById('rz-host-css')) return;
    var st = document.createElement('style');
    st.id = 'rz-host-css';
    st.appendChild(document.createTextNode(
      '#' + HOST_ID + '.rz-float{position:fixed;top:0;right:0;bottom:0;left:0;' +
      'z-index:2147483000;overflow-y:auto;-webkit-overflow-scrolling:touch;' +
      'background:#F4F1EA}'));
    (document.head || document.documentElement).appendChild(st);
  }

  /* The host page paints its own content, and its order form, in the second before this
     file has even finished downloading. A man saw a checkout he had not asked for, and a
     white page, and could scroll away from a quiz that had not arrived yet.

     So the paste snippet carries an opaque sheet of paper as inline CSS, which the browser
     honours on the first paint. This takes it away the moment there is a funnel underneath
     it instead. If this file never arrives, the sheet stays, which is the right failure:
     a blank page beats somebody's half drawn checkout. */
  function unveil(){
    try{
      var v = document.getElementById('rz-veil');
      if (v && v.parentNode) v.parentNode.removeChild(v);
      var vs = document.getElementById('rz-veil-css');
      if (vs && vs.parentNode) vs.parentNode.removeChild(vs);
    }catch(e){}
  }

  function paint(){
    try{
      var st = document.createElement('style');
      st.setAttribute('data-rz-funnel','1');
      st.appendChild(document.createTextNode(CSS));
      (document.head || document.documentElement).appendChild(st);
      sheet();
      var host = document.getElementById(HOST_ID);
      if (!host){
        host = document.createElement('div');
        host.id = HOST_ID;
      }
      if (hostRoot() && mountDiv()){
        /* their page: start over it, and go into the flow when it is safe */
        (document.body || document.documentElement).appendChild(host);
        host.className = 'rz-float';
      } else if (!host.parentNode){
        /* a bare page: where the tag sits, or failing that the end of the body */
        var m = mountDiv();
        if (m) m.appendChild(host);
        else {
          var sc = document.currentScript;
          if (sc && sc.parentNode) sc.parentNode.insertBefore(host, sc.nextSibling);
          else (document.body || document.documentElement).appendChild(host);
        }
      }
      host.innerHTML = HTML;
    }catch(e){
      if (window.console && console.error) console.error('[RZ] could not paint the funnel', e);
      return false;
    }
    return true;
  }

  /* lift the sheet into the page, keeping his place in it */
  function home(){
    var m = mountDiv(), h = document.getElementById(HOST_ID);
    /* Nothing to move is still settled. Returning quietly here once left anything waiting
       on the handover sat there until the fifteen second fallback fired. */
    if (!m || !h || h.parentNode === m) { settled(); return; }
    var inner = 0;
    try{ inner = h.scrollTop || 0; }catch(e){}
    m.appendChild(h);
    h.className = '';
    try{
      if (inner > 0){
        var top = Math.round(h.getBoundingClientRect().top + window.pageYOffset);
        window.scrollTo(0, top + inner);
      }
    }catch(e){}
    /* the quiz measures the room it has, and it has just been given a different one */
    try{ if (window.RZ && RZ.fitQuiz) RZ.fitQuiz(); }catch(e){}
    settled();
  }

  /* Moving this subtree re-parents everything in it, and a video player that has already
     wired itself to a node loses that node and refuses to start. Wistia says so out loud:
     "Could not find element in DOM. Failed to initialize video." So nothing that embeds
     anything is built until the funnel has stopped moving. */
  function settled(){
    if (window.__rzSettled) return;
    window.__rzSettled = true;
    try{ window.dispatchEvent(new Event('rz:settled')); }catch(e){}
  }
  window.__rzWhenSettled = function(fn){
    if (window.__rzSettled) { try{ fn(); }catch(e){} return; }
    var done = false;
    function go(){ if (done) return; done = true; try{ fn(); }catch(e){} }
    window.addEventListener('rz:settled', go, {once:true});
    /* a page that never settles still has to show its film */
    setTimeout(function(){ settled(); go(); }, 15000);
  };

  /* Wait for the host's checkout to finish drawing, then take the funnel out of its own
     floating sheet and put it into the page. Anything that wants to happen after that
     hands in a callback. */
  function handover(done){
    if (!hostRoot() || !mountDiv()) { settled(); if (done) done(); return; }
    var t0 = Date.now();
    (function poll(){
      var hasOrder = false;
      try{ hasOrder = !!document.querySelector('.c-order, [id^="one-step-order-"]'); }catch(e){}
      var budget = hasOrder ? ORDER_LIMIT : LIMIT;
      if (hostReady() || Date.now() - t0 > budget) { home(); if (done) done(); return; }
      setTimeout(poll, 40);
    })();
  }
  window.__rzHandover = handover;

  function start(){
    if (!paint()) return;
    /* the funnel's own code, verbatim, with the markup already on the page */
    (function(){
    'use strict';
    var ROOT=null;
    function root(){ return ROOT || (ROOT=document.getElementById('rz-thanks')); }
    var RZT={
      id  : function(x){ var r=root(); return r?r.querySelector('#'+x):null; },
      one : function(x){ var r=root(); return r?r.querySelector(x):null; },
      all : function(x){ var r=root(); return r?r.querySelectorAll(x):[]; }
    };
    /* a page with no charset decodes this file as Latin-1 and the script dies, so the
       fragment is pure ASCII; a page with no viewport meta lays out at 980px, so add one */
    try{
      if(!document.querySelector('meta[charset], meta[http-equiv="Content-Type"]')){
        var mc=document.createElement('meta'); mc.setAttribute('charset','utf-8');
        (document.head||document.documentElement).insertBefore(mc,(document.head||document.documentElement).firstChild);
      }
      if(!document.querySelector('meta[name="viewport"]')){
        var mv=document.createElement('meta'); mv.name='viewport';
        mv.content='width=device-width,initial-scale=1,viewport-fit=cover';
        (document.head||document.documentElement).appendChild(mv);
      }
    }catch(e){}

    /* ---------- the film. paste the whole Wistia snippet or just the media id ---------- */
    var THANKS_WISTIA = '<wistia-player media-id="7ehs06hu2p" aspect="1.5434083601286173"></wistia-player>';
    try{(function(){
      var raw=String(THANKS_WISTIA||'').trim(); if(!raw) return;
      var build=function(){
      var m=raw.match(/media-id=["']([A-Za-z0-9]+)["']/)
          || raw.match(/medias\/([A-Za-z0-9]+)/)
          || raw.match(/embed\/([A-Za-z0-9]+)\.js/)
          || (/^[A-Za-z0-9]+$/.test(raw) ? [null, raw] : null);
      if(!m) return;
      var id=m[1];
      var am=raw.match(/aspect=["']([0-9.]+)["']/);
      var aspect=am?parseFloat(am[1]):0;
      var vid=RZT.id('vid'); if(!vid) return;
      var ph=RZT.id('vidph'); if(ph) ph.parentNode.removeChild(ph);
      vid.hidden=false;
      if(aspect>0.2&&aspect<5){ vid.style.aspectRatio=String(aspect); }
      function js(src,mod){ var t=document.createElement('script'); t.src=src; t.async=true;
        if(mod) t.type='module'; document.head.appendChild(t); }
      js('https://fast.wistia.com/player.js',false);
      js('https://fast.wistia.com/embed/'+id+'.js',true);
      var pl=document.createElement('wistia-player');
      pl.setAttribute('media-id',id);
      if(aspect) pl.setAttribute('aspect',String(aspect));
      vid.appendChild(pl);
      };
      /* the loader is about to lift this stage into the page, and a player built before that
         move loses the node it wired itself to */
      if(typeof window.__rzWhenSettled === 'function') window.__rzWhenSettled(build);
      else build();
    })();}catch(e){}

    (function(){
    'use strict';
    /* ===================================================================== FILL THESE IN */
    /* The Fitting Room, the scan and the way to reach him all arrive by email, so this page
       does not carry a link to any of them. Three buttons here would be three more things to
       keep in step with whatever the email actually says. */
    var VIDEO            = { iframe:'', file:'', poster:'' };
    /* the booked slot. the booking platform can pass ?when=2026-09-22T15:30 and ?tz=Europe/London,
       otherwise the page says "in your calendar" and never invents a time. */
    /* ===================================================================== */

    var $=function(id){ return RZT.id(id); };
    var RM=false; try{ RM=matchMedia('(prefers-reduced-motion:reduce)').matches; }catch(e){}
    function qp(k){ try{ return new URLSearchParams(location.search).get(k); }catch(e){ return null; } }

    /* The stub used to read "Order 0201" for every single buyer. A made up number on a receipt
       is a small lie that two men comparing notes would catch, so it now says "Paid" unless
       the checkout actually hands us an order id. */
    function paintTicket(){
      var el=RZT.id('ticket-no'); if(!el) return;
      var id = qp('order_id')||qp('orderId')||qp('transaction_id')||qp('payment_id');
      if(!id) return;
      id=String(id).replace(/[^A-Za-z0-9]/g,'');
      if(id.length<4) return;
      el.textContent='Order '+id.slice(-6).toUpperCase();
    }

    /* ---------- reveals first, so nothing can ever be left invisible ---------- */
    try{
      var rises=[].slice.call(RZT.all('.rise'));
      if(RM||!('IntersectionObserver' in window)){ rises.forEach(function(e){ e.classList.add('in'); }); }
      else{ var io=new IntersectionObserver(function(es){ es.forEach(function(e){ if(!e.isIntersecting) return;
          e.target.classList.add('in'); io.unobserve(e.target); }); },{threshold:0,rootMargin:'0px 0px -5% 0px'});
        rises.forEach(function(e){ io.observe(e); }); }
    }catch(e){ [].forEach.call(RZT.all('.rise'),function(e){ e.classList.add('in'); }); }

    /* ---------- the basting stitches draw themselves. a clipped element never intersects,
         so an observer on it can never fire. driven off scroll position instead. ---------- */
    var DRAWS=[], drawRaf=0;
    try{ DRAWS=[].slice.call(RZT.all('.baste'));
         if(RM){ DRAWS.forEach(function(b){ b.classList.add('in'); }); DRAWS=[]; } }catch(e){}
    function drawPass(){ drawRaf=0; if(!DRAWS.length) return;
      var vh=window.innerHeight,i=DRAWS.length;
      while(i--){ var r=DRAWS[i].getBoundingClientRect();
        if(r.top<vh*.9&&r.bottom>0){ DRAWS[i].classList.add('in'); DRAWS.splice(i,1); } } }
    function drawReq(){ if(!drawRaf) drawRaf=requestAnimationFrame(drawPass); }
    try{ addEventListener('scroll',drawReq,{passive:true}); addEventListener('resize',drawReq,{passive:true}); drawReq(); }catch(e){}

    /* ---------- who he is. same contract as the sales page. ---------- */
    var YOU={};
    try{
      var st={}; try{ st=JSON.parse(localStorage.getItem('renz_you')||localStorage.getItem('renz_score')||'{}')||{}; }catch(e){ st={}; }
      function name(v){ v=(v||'').toString().trim().split(/\s+/)[0].replace(/[^A-Za-z\u00C0-\u00FF'\u2019\-]/g,'').slice(0,18);
        if(v.length<2) return ''; return v.toLowerCase().replace(/(^|[\-'\u2019])([a-z\u00E0-\u00FF])/g,function(m,x,y){ return x+y.toUpperCase(); }); }
      /* GoHighLevel's own merge field is {{contact.first_name}}, so the redirect after a
         booking naturally carries first_name. Taking it before anything in storage means
         the page greets the man who just booked, not whoever used this browser last. */
      YOU.name = name(qp('first_name')||qp('firstName')||qp('fn')||qp('name')||st.name);
      YOU.want = ({deals:1,respect:1,dates:1,easy:1}[qp('want')||st.want]) ? (qp('want')||st.want) : '';
      YOU.lid  = qp('lid')||st.lid||'';
    }catch(e){}

    /* ---------- his name, and the same order number he was given on the way in ---------- */
    try{
      if(YOU.name){
        /* This runs before the time has been read, so it cannot know whether he has booked.
           It only records his name. The calendar block below picks the sentence. */
        window.__rzName = YOU.name;
        $('doc-name').textContent=YOU.name;
      }
      var WANT={deals:'walk in believed',respect:'be taken seriously from the start',
                dates:'be the one people notice',easy:'never think about it again'}[YOU.want];
      if(WANT) $('sub').innerHTML='Most men mean to sort this out and never do. You just did. <b>Now we get you what you came for.</b>';
    }catch(e){}

    /* ---------- the booked slot, only ever said if the booking passed one ---------- */
    try{
      /* GoHighLevel names this differently depending on how the redirect is set up, and the
         name is easy to get wrong by one character. Rather than demand one exact spelling,
         take the first parameter that looks like a date we can read. */
      var WHEN_KEYS=['when','start_time','startTime','event_start_time','eventStartTime',
                     'appointment_start_time','appointmentStartTime','selected_slot','slot',
                     'start','date','datetime','appointment_time'];
      var when='';
      try{
        var qs=new URLSearchParams(location.search);
        for(var wi=0; wi<WHEN_KEYS.length && !when; wi++){
          var cand=qs.get(WHEN_KEYS[wi]);
          if(cand && !isNaN(new Date(cand).getTime())) when=cand;
        }
        /* last resort: any parameter at all whose value parses as a date with a year in it */
        if(!when){ qs.forEach(function(v){
          if(!when && v && /\d{4}/.test(v) && !isNaN(new Date(v).getTime())) when=v; }); }
      }catch(e){}
      if(when){ try{ localStorage.setItem('renz_when',when); }catch(e){} }
      else { try{ when=localStorage.getItem('renz_when')||''; }catch(e){} }
      /* ---------------------------------------------------------------- the calendar
         He has paid but he has not picked a time, so the booking widget goes on this page
         and he never leaves to do it. Once there IS a time, the calendar is replaced by
         the time, because offering a man a calendar he has already used is confusing. */
      (function(){
        var CAL  = 'https://api.leadconnectorhq.com/widget/booking/RYS7dx7Mc0qtjARUFxLP';
        var wrap = $('cal'), slot = $('slot');
        if(!wrap) return;

        var wasBooked = false;
        try{ wasBooked = localStorage.getItem('renz_booked') === '1'; }catch(e){}
        var booked = !!(when && !isNaN(new Date(when).getTime())) || wasBooked;
        var nm = window.__rzName ? ', ' + window.__rzName : '';

        /* A man who arrives with his time already picked was being told, four lines under
           "Your Call Is Booked", to go and pick a time, with a button that scrolled him to a
           calendar that is not on the page any more. Step one is done, so say it is done.
           The worklist wakes up after this, so the tick is handed over rather than clicked. */
        if(booked){
          window.__rzStepOneDone = true;
          try{ $('job-book-p').innerHTML = 'Your time is held, and it is written at the top of '
            + 'this page. <b>Now the other three.</b>'; }catch(e){}
        }

        /* Booked is a different sentence from paid. Telling a man his call is booked while
           he is still staring at an empty calendar is how he decides it is already done and
           closes the tab. */
        try{
          if(booked){
            $('h1').textContent = 'Your Call Is Booked' + nm + '.';
            $('lede').innerHTML = 'Your time is held.<br>We start on your numbers today.'
              + '<br><b>You have stopped putting it off.</b>';
          } else {
            $('h1').textContent = 'Right. You\u2019re In' + nm + '.';
            $('lede').innerHTML = 'The call is paid for.<br>One thing left, and it takes ten '
              + 'seconds.<br><b>Pick your time, just under this video.</b>';
          }
        }catch(e){}

        /* and the way back, wired once, whichever way he got here */
        var again = $('again');
        if(again){
          var link = $('again-a');
          if(link) link.addEventListener('click', function(e){
            e.preventDefault();
            try{ localStorage.removeItem('renz_booked'); }catch(e2){}
            try{ localStorage.removeItem('renz_when'); }catch(e2){}
            /* the page cannot go on saying his call is booked while he is stood in front of
               an open calendar looking for another one */
            try{
              $('h1').textContent = 'Pick Your New Time' + nm + '.';
              /* Booking again does not drop the first one, so do not let him think it does.
                 Either he cancels it from the email, or he messages Lorenzo, who moves it. */
              $('lede').innerHTML = 'Take whichever slot suits you better.'
                + '<br>Then drop the first one with the link in your confirmation email.'
                + '<br><b>Or message me and I\u2019ll move it for you.</b>';
            }catch(e2){}
            if(slot) slot.hidden = true;
            again.hidden = true;
            wrap.hidden = false;
            [].forEach.call(RZT.all('[data-tocal]'),function(a){ a.hidden = false; });
            try{ wrap.scrollIntoView({behavior:'smooth', block:'start'}); }catch(e2){ wrap.scrollIntoView(); }
            build();
          });
        }

        if(booked){
          wrap.hidden = true;
          if(slot) slot.hidden = false;
          if(again) again.hidden = false;
          /* the calendar has just left the page, so the button that scrolls to it goes too */
          [].forEach.call(RZT.all('[data-tocal]'),function(a){ a.hidden = true; });
          return;
        }
        if(slot) slot.hidden = true;
        wrap.hidden = false;
        build();

        /* Named and guarded, because the calendar is drawn either on arrival or later, when a
           man who has already booked asks for a different time. Twice would be two calendars. */
        function build(){
        if(wrap.querySelector('.cal-frame iframe')) return;

        /* carry across whatever we already know, so he is not typing it a third time */
        var url = CAL, q = [];
        try{
          var sp = new URLSearchParams(location.search);
          var st = {};
          try{ st = JSON.parse(localStorage.getItem('renz_score')||'{}')||{}; }catch(e){}
          var fn = sp.get('first_name')||sp.get('firstName')||sp.get('fn')||st.first_name||'';
          var ln = sp.get('last_name')||sp.get('lastName')||st.last_name||'';
          var em = sp.get('email')||st.email||'';
          if(fn) q.push('first_name='+encodeURIComponent(fn));
          if(ln) q.push('last_name='+encodeURIComponent(ln));
          if(em) q.push('email='+encodeURIComponent(em));
          if(q.length) url += (url.indexOf('?')>-1?'&':'?') + q.join('&');
        }catch(e){}

        var frame = document.createElement('iframe');
        frame.src = url;
        frame.title = 'Pick a time for your Style Solve call';
        frame.setAttribute('scrolling','no');
        frame.addEventListener('load', function(){
          var l = $('cal-load'); if(l) l.parentNode.removeChild(l);
        });
        var box = wrap.querySelector('.cal-frame');
        if(box) box.appendChild(frame);

        /* GoHighLevel resizes its own embed through this */
        if(!RZT.one('script[src*="form_embed.js"]')){
          var s2 = document.createElement('script');
          s2.src = 'https://link.msgsndr.com/js/form_embed.js';
          s2.async = true;
          document.head.appendChild(s2);
        }
        }

        /* the link inside step one */
        [].forEach.call(RZT.all('[data-tocal]'), function(a){
          if(booked){ a.hidden = true; return; }
          a.addEventListener('click', function(e){
            e.preventDefault();
            try{ wrap.scrollIntoView({behavior:'smooth', block:'start'}); }
            catch(e2){ wrap.scrollIntoView(); }
          });
        });

        /* He picks his time here, in the calendar on this page, so nothing reloads and no
           redirect fires. When the widget says it is done, this page has to stop asking him
           to pick a time and start telling him when it is. If the widget never says anything,
           nothing breaks: he ticks step one himself like the other three.

           The widget's own code posts ["msgsndr-booking-complete",{fingerprint,calendarId}]
           to its parent the moment an appointment is made, and that is the one we are really
           waiting for. The rest are there in case they rename it. The words are deliberately
           narrow: "appointment" on its own turns up in the widget's housekeeping messages,
           and acting on that would take the calendar away from a man who has not booked yet.

           Note what is NOT in that payload: the time. So the page says his call is booked and
           leaves the slot reading Confirmed, rather than inventing an hour he never picked. */
        var settled = false;
        window.addEventListener('message', function(ev){
          if(settled) return;
          if(!/leadconnectorhq|msgsndr/i.test(ev.origin||'')) return;
          var txt = '';
          try{ txt = typeof ev.data === 'string' ? ev.data : JSON.stringify(ev.data||''); }catch(e){ return; }
          if(!/msgsndr-booking-complete|booking[_-](?:success|complete)|appointment_booked|appointment_scheduled|\bbooked\b|\bscheduled\b/i.test(txt)) return;
          settled = true;

          var li = $('job-book');
          if(li){
            var box2 = li.querySelector('[data-tick]');
            if(box2 && box2.getAttribute('aria-checked') !== 'true') box2.click();
          }

          var found = '';
          try{
            var m = txt.match(/\d{4}-\d{2}-\d{2}[T ][\d:]{5,}(?:[.\d]*)?(?:Z|[+-]\d{2}:?\d{2})?/);
            if(m && !isNaN(new Date(m[0]).getTime())) found = m[0];
          }catch(e){}
          try{ localStorage.setItem('renz_booked','1'); }catch(e){}
          if(found){ try{ localStorage.setItem('renz_when', found); }catch(e){} }

          /* his own confirmation inside the widget gets a moment before we take it away */
          setTimeout(function(){
            try{
              $('h1').textContent = 'Your Call Is Booked' + nm + '.';
              $('lede').innerHTML = 'Your time is held.<br>We start on your numbers today.'
                + '<br><b>You have stopped putting it off.</b>';
            }catch(e){}
            try{
              if(found && window.__rzPaintTime) window.__rzPaintTime(new Date(found));
            }catch(e){}
            if(slot) slot.hidden = false;
            if(again) again.hidden = false;
            wrap.hidden = true;
            [].forEach.call(RZT.all('[data-tocal]'),function(a){ a.hidden = true; });
            try{ window.scrollTo(0,0); }catch(e){}
          }, 1400);
        }, false);
      })();

      /* Named, because a man who picks his time in the calendar on this page has to be
         able to see it written out without the page reloading under him. */
      function paintTime(d){
        if(!(d&&!isNaN(d.getTime()))) return false;
        var DAY=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
            MON=['January','February','March','April','May','June','July','August','September','October','November','December'];
        var hh=d.getHours(), mm=d.getMinutes();
        var t=((hh%12)||12)+(mm?':'+('0'+mm).slice(-2):'')+(hh<12?'am':'pm');
        $('slot-val').innerHTML=DAY[d.getDay()]+' '+d.getDate()+' '+MON[d.getMonth()]+
          '<em>'+t+' &middot; forty five minutes, one to one</em>';
        /* a real calendar file, built in his browser, no server needed */
        var end=new Date(d.getTime()+45*60000);
        function z(n){ return ('0'+n).slice(-2); }
        function ics(x){ return x.getUTCFullYear()+z(x.getUTCMonth()+1)+z(x.getUTCDate())+'T'+z(x.getUTCHours())+z(x.getUTCMinutes())+'00Z'; }
        var TITLE='The Style Solve with Lorenzo';
        var NOTE='Forty five minutes, one to one. Somewhere quiet, camera on, and near your closet if you can.';
        var gcal='https://calendar.google.com/calendar/render?action=TEMPLATE'+
          '&text='+encodeURIComponent(TITLE)+
          '&dates='+ics(d)+'/'+ics(end)+
          '&details='+encodeURIComponent(NOTE);
        [].forEach.call(RZT.all('[data-cal]'),function(a){
          a.setAttribute('href',gcal); a.setAttribute('target','_blank'); a.setAttribute('rel','noopener');
          a.removeAttribute('data-inert'); a.hidden=false; });

        /* and the file, for a man who does not use Google. only offered where a save can actually happen. */
        var icsText=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Renz Tailors//Style Solve//EN','BEGIN:VEVENT',
          'UID:'+(YOU.lid||'renz')+'@renztailors','DTSTAMP:'+ics(new Date()),'DTSTART:'+ics(d),'DTEND:'+ics(end),
          'SUMMARY:'+TITLE,'DESCRIPTION:'+NOTE,'END:VEVENT','END:VCALENDAR'].join('\r\n');
        var icsBtn=$('cal-file');
        if(icsBtn){
          if(window.claude&&window.claude.use){
            window.claude.use('downloads').then(function(dl){
              if(!dl) return;
              icsBtn.hidden=false;
              icsBtn.addEventListener('click',function(e){ e.preventDefault();
                dl.save({filename:'style-solve.ics',data:icsText}); });
            }).catch(function(){});
          } else {
            icsBtn.hidden=false;
            icsBtn.setAttribute('href','data:text/calendar;charset=utf-8,'+encodeURIComponent(icsText));
            icsBtn.setAttribute('download','style-solve.ics');
          }
        }
        return true;
      }
      /* Before he has picked a time there is no calendar entry to add, so the button had no
         address and a tap did nothing except tick step four off. It stays away until the slot
         is known, which is the moment it can actually do its job. */
      [].forEach.call(RZT.all('[data-cal]'),function(a){
        if(!/^https?:/.test(a.getAttribute('href')||'')){ a.setAttribute('data-inert','1'); a.hidden=true; } });
      window.__rzPaintTime = paintTime;
      paintTime(when?new Date(when):null);
      paintTicket();
    }catch(e){}

    /* ---------- the film only when it exists, and it takes what the first screen has left ---------- */
    try{
      var vid=$('vid'), ph=$('vidph');
      if(VIDEO.iframe||VIDEO.file){
        ph.remove();
        var el;
        if(VIDEO.iframe){ el=document.createElement('iframe'); el.src=VIDEO.iframe;
          el.allow='autoplay; fullscreen; picture-in-picture'; el.setAttribute('allowfullscreen',''); el.title='Three things before we speak'; }
        else { el=document.createElement('video'); el.src=VIDEO.file; el.controls=true; el.playsInline=true;
          el.setAttribute('playsinline',''); el.preload='metadata'; if(VIDEO.poster) el.poster=VIDEO.poster; }
        vid.appendChild(el);
      }
    }catch(e){}
    function fitHero(){
      try{
        var vid=$('vid'), slot=RZT.one('.slot');
        if(!vid||vid.hidden||!slot||!vid.parentNode) return;
        var vh=window.innerHeight, safety=14, col=vid.parentNode.clientWidth;
        for(var pass=0;pass<4;pass++){
          var bottom=Math.round(vid.getBoundingClientRect().bottom+window.pageYOffset);
          var cur=vid.offsetHeight||1, delta=bottom-(vh-safety);
          if(Math.abs(delta)<4) break;
          var want=Math.max(96,cur-delta);
          vid.style.setProperty('--vw-fit',Math.min(col,Math.round(want*16/9))+'px');
          vid.classList.add('fitted');
        }
      }catch(e){}
    }
    try{ fitHero(); addEventListener('resize',fitHero,{passive:true});
         addEventListener('orientationchange',function(){ setTimeout(fitHero,220); },{passive:true});
         if(document.fonts&&document.fonts.ready) document.fonts.ready.then(fitHero); }catch(e){}

    /* ---------- the worklist. it remembers, because a man comes back to this page ---------- */
    try{(function(){
      var KEY='renz_thanks', state={};
      try{ state=JSON.parse(localStorage.getItem(KEY)||'{}')||{}; }catch(e){ state={}; }
      if(window.__rzStepOneDone) state['job-book']=1;
      var jobs=[].slice.call(RZT.all('.jobs>li'));

      function save(){ try{ localStorage.setItem(KEY,JSON.stringify(state)); }catch(e){} }

      function paint(){
        var n=0;
        jobs.forEach(function(li){
          var on=!!state[li.id];
          li.classList.toggle('done',on);
          var box=li.querySelector('[data-tick]'); if(box) box.setAttribute('aria-checked',on?'true':'false');
          if(on) n++;
        });
        /* the denominator follows the list. it was pinned at three while four steps were on
           the page, so a man who finished them all was told "4 of three done, -1 to go". */
        var total=jobs.length||1;
        $('pg-n').textContent=n; $('pg-left').textContent=Math.max(0,total-n);
        var d=$('pg-d'); if(d) d.textContent=(['none','one','two','three','four','five','six'][total]||total);
        $('pg-bar').style.width=Math.round(n/total*100)+'%';
        [].forEach.call(RZT.all('#recap li'),function(li){
          li.classList.toggle('done',!!state[li.getAttribute('data-for')]); });

        /* the style guide fills the moment the scan is in. that is the whole point of step two. */
        var scan=!!state['job-scan'];
        [].forEach.call(RZT.all('#doc-rows li[data-need="scan"]'),function(li,i){
          li.classList.toggle('filled',scan);
          var b=li.querySelector('b');
          if(b) b.textContent = scan ? 'in' : (i>=3 ? 'waiting on the photos' : 'waiting on the scan');
          if(!RM) li.style.transitionDelay=(scan?i*90:0)+'ms';
        });
        var cap=$('doc-cap');
        if(cap) cap.innerHTML = scan
          ? 'Five of the eight are in. <b>The rest gets written on the call.</b>'
          : 'Nothing in it yet. <b>The scan is what starts it.</b>';
      }

      function toggle(li){
        state[li.id]=!state[li.id];
        if(!state[li.id]) delete state[li.id];
        save(); paint();
      }

      jobs.forEach(function(li){
        var top=li.querySelector('[data-open]'), box=li.querySelector('[data-tick]');
        top.addEventListener('click',function(e){
          if(e.target.closest('[data-tick]')) return;
          var open=li.classList.toggle('open');
          top.setAttribute('aria-expanded',open?'true':'false');
        });
        box.addEventListener('click',function(e){ e.stopPropagation(); toggle(li); });
        box.addEventListener('keydown',function(e){
          if(e.key===' '||e.key==='Enter'){ e.preventDefault(); e.stopPropagation(); toggle(li); } });
      });

      /* the one that matters most is open when he lands */
      var scanLi=$('job-scan');
      if(scanLi&&!state['job-scan']){ scanLi.classList.add('open');
        scanLi.querySelector('[data-open]').setAttribute('aria-expanded','true'); }

      /* Adding the call to his calendar is the one job left on this page that is still a
         button, so it is the one job that can still tick itself off. The email, the scan and
         The Fitting Room all happen in his inbox, where this page cannot see them, so he
         ticks those three himself. */
      [].forEach.call(RZT.all('[data-cal]'),function(a){
        a.addEventListener('click',function(){ if(a.hasAttribute('data-inert')) return;
          if(!state['job-cal']){ state['job-cal']=1; save(); paint(); } }); });

      paint();
    })();}catch(e){}
    })();

    })();
    unveil();
    /* A stage with a quiz on it keeps the host page covered until the man is through it,
       and asks for the handover itself. Everything else goes in as soon as it is safe. */
    if (!window.__RZ_DEFER_HOME) handover();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', start, {once:true});
  } else {
    start();
  }
})();
